#!/bin/bash

if [ -f /etc/arch-release ]; then
    # For Arch-based systems
    sudo pacman -Syu
    sudo pacman -Rns $(pacman -Qdtq)
    sudo pacman -Sc
else
    # For Ubuntu/Pop!_OS-based systems
    sudo apt update
    sudo apt upgrade -y
    sudo apt autopurge -y && sudo apt autoremove -y && sudo apt clean
fi

# Common for both
sudo composer global selfupdate
composer global update -vv --profile
sudo npm-check -gui

