# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #fbf1c7
background              #282828
selection_foreground    #282828
selection_background    #fbf1c7

# Cursor colors
cursor                  #fbf1c7
cursor_text_color       #282828

# Scrollbar colors
scrollbar_handle_color  #bdae93
scrollbar_track_color   #504945

# URL color when hovering with mouse
url_color               #fbf1c7

# Kitty window border colors
active_border_color     #d3869b
inactive_border_color   #928374
bell_border_color       #fabd2f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1d2021
active_tab_background   #d3869b
inactive_tab_foreground #fbf1c7
inactive_tab_background #1d2021
tab_bar_background      #1d2021

# Colors for marks (marked text in the terminal)
mark1_foreground #282828
mark1_background #d3869b
mark2_foreground #282828
mark2_background #d3869b
mark3_foreground #282828
mark3_background #458588

# The 16 terminal colors

# black
color0 #504945
color8 #665c54

# red
color1 #fb4934
color9 #fb4934

# green
color2  #b8bb26
color10 #b8bb26

# yellow
color3  #fabd2f
color11 #fabd2f

# blue
color4  #83a598
color12 #83a598

# magenta
color5  #d3869b
color13 #d3869b

# cyan
color6  #8ec07c
color14 #8ec07c

# white
color7  #ebdbb2
color15 #d5c4a1
