# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#191724"

# Main text color
theme[main_fg]="#e0def4"

# Title color for boxes
theme[title]="#e0def4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#31748f"

# Background color of selected item in processes box
theme[selected_bg]="#403d52"

# Foreground color of selected item in processes box
theme[selected_fg]="#31748f"

# Color of inactive/disabled text
theme[inactive_fg]="#6e6a86"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#ebbcba"

# Background color of the percentage meters
theme[meter_bg]="#403d52"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ebbcba"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#c4a7e7" #Mauve
theme[mem_box]="#9ccfd8" #Green
theme[net_box]="#eb6f92" #Maroon
theme[proc_box]="#31748f" #Blue

# Box divider line and small boxes line color
theme[div_line]="#6e6a86"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#9ccfd8"
theme[temp_mid]="#f6c177"
theme[temp_end]="#eb6f92"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#9ccfd8"
theme[cpu_mid]="#31748f"
theme[cpu_end]="#c4a7e7"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#c4a7e7"
theme[free_mid]="#c4a7e7"
theme[free_end]="#31748f"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#31748f"
theme[cached_mid]="#31748f"
theme[cached_end]="#c4a7e7"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#f6c177"
theme[available_mid]="#eb6f92"
theme[available_end]="#eb6f92"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#9ccfd8"
theme[used_mid]="#9ccfd8"
theme[used_end]="#9ccfd8"

# Download graph colors (Peach -> Red)
theme[download_start]="#f6c177"
theme[download_mid]="#eb6f92"
theme[download_end]="#eb6f92"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#9ccfd8"
theme[upload_mid]="#9ccfd8"
theme[upload_end]="#9ccfd8"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#31748f"
theme[process_mid]="#c4a7e7"
theme[process_end]="#c4a7e7"