# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #e0def4
background              #191724
selection_foreground    #191724
selection_background    #e0def4

# Cursor colors
cursor                  #e0def4
cursor_text_color       #191724

# Scrollbar colors
scrollbar_handle_color  #908caa
scrollbar_track_color   #403d52

# URL color when hovering with mouse
url_color               #e0def4

# Kitty window border colors
active_border_color     #c4a7e7
inactive_border_color   #6e6a86
bell_border_color       #f6c177

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #13111e
active_tab_background   #c4a7e7
inactive_tab_foreground #e0def4
inactive_tab_background #1f1d2e
tab_bar_background      #13111e

# Colors for marks (marked text in the terminal)
mark1_foreground #191724
mark1_background #c4a7e7
mark2_foreground #191724
mark2_background #c4a7e7
mark3_foreground #191724
mark3_background #31748f

# The 16 terminal colors

# black
color0 #403d52
color8 #524f67

# red
color1 #eb6f92
color9 #eb6f92

# green
color2  #9ccfd8
color10 #9ccfd8

# yellow
color3  #f6c177
color11 #f6c177

# blue
color4  #31748f
color12 #31748f

# magenta
color5  #c4a7e7
color13 #c4a7e7

# cyan
color6  #9ccfd8
color14 #9ccfd8

# white
color7  #908caa
color15 #908caa
