local o = vim.opt
local g = vim.g

o.autoindent = true
o.autoread = true
o.backup = false
o.breakindent = true
-- o.cmdheight = 0
o.encoding = "utf-8"
o.expandtab = true
o.fileencoding = "utf-8"
o.hlsearch = false
o.incsearch = true
o.number = true
o.relativenumber = true
o.scrolloff = 8
o.shiftwidth = 2
o.showcmd = true
o.sidescrolloff = 8
o.smartindent = true
o.smarttab = true
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.tabstop = 2
o.termguicolors = true
o.title = true
o.wrap = false

g.netrw_altv = 1
g.netrw_banner = 0
g.netrw_browse_split = 0
g.netrw_liststyle = 1
g.netrw_winsize = 25
