# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #dcd7ba
background              #1f1f28
selection_foreground    #1f1f28
selection_background    #dcd7ba

# Cursor colors
cursor                  #dcd7ba
cursor_text_color       #1f1f28

# Scrollbar colors
scrollbar_handle_color  #727169
scrollbar_track_color   #2a2a37

# URL color when hovering with mouse
url_color               #dcd7ba

# Kitty window border colors
active_border_color     #8992b2
inactive_border_color   #54546d
bell_border_color       #e6c384

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #16161d
active_tab_background   #957fb8
inactive_tab_foreground #dcd7ba
inactive_tab_background #16161d
tab_bar_background      #16161d

# Colors for marks (marked text in the terminal)
mark1_foreground #1f1f28
mark1_background #8992b2
mark2_foreground #1f1f28
mark2_background #957fb8
mark3_foreground #1f1f28
mark3_background #6a9589

# The 16 terminal colors

# black
color0 #2a2a37
color8 #363646

# red
color1 #e46876
color9 #e46876

# green
color2  #98bb6c
color10 #98bb6c

# yellow
color3  #e6c384
color11 #e6c384

# blue
color4  #7e9cd8
color12 #7e9cd8

# magenta
color5  #d2869c
color13 #d2869c

# cyan
color6  #7aa89f
color14 #7aa89f

# white
color7  #a9a9b8
color15 #a9a9b8
