general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = pidof hyprlock || hyprlock    # lock before suspend.
    after_sleep_cmd = pidof hyprlock || hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
    timeout = 600                                 # 10min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 630                                                     # 10.5min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'                            # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })' && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 1800                                # 30min
    on-timeout = $HOME/.config/hypr/lock-and-suspend.sh
}
