-- Generated by nwg-displays on 2026-07-31 at 10:30:27. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.05",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@50.0",
    position = "3840x0",
    scale = 1.0
})
