-- Generated by nwg-displays on 2026-09-07 at 09:15:55. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.05",
    position = "2304x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "4224x0",
    scale = 1,
    vrr = 0
})
