# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#282828"

# Main text color
theme[main_fg]="#fbf1c7"

# Title color for boxes
theme[title]="#fbf1c7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#83a598"

# Background color of selected item in processes box
theme[selected_bg]="#504945"

# Foreground color of selected item in processes box
theme[selected_fg]="#83a598"

# Color of inactive/disabled text
theme[inactive_fg]="#a89984"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#fbf1c7"

# Background color of the percentage meters
theme[meter_bg]="#504945"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#fbf1c7"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#d3869b" #Mauve
theme[mem_box]="#b8bb26" #Green
theme[net_box]="#cc241d" #Maroon
theme[proc_box]="#83a598" #Blue

# Box divider line and small boxes line color
theme[div_line]="#928374"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#b8bb26"
theme[temp_mid]="#fabd2f"
theme[temp_end]="#fb4934"

# CPU graph colors (Teal -> Lavender)
theme[cpu_start]="#8ec07c"
theme[cpu_mid]="#458588"
theme[cpu_end]="#d3869b"

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]="#d3869b"
theme[free_mid]="#d3869b"
theme[free_end]="#83a598"

# Mem/Disk cached meter (Sapphire -> Lavender)
theme[cached_start]="#458588"
theme[cached_mid]="#83a598"
theme[cached_end]="#d3869b"

# Mem/Disk available meter (Peach -> Red)
theme[available_start]="#fe8019"
theme[available_mid]="#cc241d"
theme[available_end]="#fb4934"

# Mem/Disk used meter (Green -> Sky)
theme[used_start]="#b8bb26"
theme[used_mid]="#8ec07c"
theme[used_end]="#83a598"

# Download graph colors (Peach -> Red)
theme[download_start]="#fe8019"
theme[download_mid]="#cc241d"
theme[download_end]="#fb4934"

# Upload graph colors (Green -> Sky)
theme[upload_start]="#b8bb26"
theme[upload_mid]="#8ec07c"
theme[upload_end]="#83a598"

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
theme[process_start]="#458588"
theme[process_mid]="#d3869b"
theme[process_end]="#d3869b"