return {
  -- "nvim-neo-tree/neo-tree.nvim",
  -- branch = "v3.x",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
  --   "MunifTanjim/nui.nvim",
  -- },
  -- config = function()
  --   require("neo-tree").setup({
  --     close_if_last_window = true,
  --     log_level = "warn",
  --     window = {
  --       position = "right",
  --     },
  --     filesystem = {
  --       hijack_netrw_behavior = "disabled"
  --     }
  --   })
  -- end
}
